### PR TITLE
trendmicrovisionne: Bug Fix - Updated get_endpoint_info to accept multiple endpoints in comma separated string.

### PR DESCRIPTION
**Pull request by shaqnawe**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Get endpoint info now accepts multiple endpoints in a comma separated string.

## What is the new behavior? (OPTIONAL)
- Multiple endpoint data can now be queried per request. Some missing response values from forensic file info are now correctly returned to user.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by shaqnawe** [comment]
@hardik-crest I tried committing after removing requests module from json file and wheels folder but it kept getting automatically added. I have enabled "Allow edits by maintainers". Please let me know if anything else needs to happen from my side. Thank you!

**Comment by hardik-crest** [comment]
> @hardik-crest I tried committing after removing requests module from json file and wheels folder but it kept getting automatically added. I have enabled "Allow edits by maintainers". Please let me know if anything else needs to happen from my side. Thank you!

Hello @shaqnawe ,
Requests module is a sub dependency of **pytmv1** module. Therefore, when pre-commit hooks run it is added back in the JSON and Wheel files. You need to remove the requests modules files from JSON and Wheel files and then commit using the **--no-verify** flag. This will resolve your issue.

Please let me know in case you have any other query.

**Comment by shaqnawe** [comment]
@hardik-crest I have removed requests from json and wheels/shared. the only remaining error I see states that the license for pytmv1 0.5.6 needs revision. Thank you for your assistance.

**Comment by shaqnawe** [comment]
Hey @hardik-crest 
I'm done updating the code and it's ready for merge. The only error remaining is the one regarding pytmv1 license. How can I go about resolving it? Is that something the Splunk team will do? Please let me know if anything else is needed from my end. Thank you for your assistance.

**Comment by shaqnawe** [comment]
@hardik-crest Thank you for the update.

**Comment by shaqnawe** [comment]
@hardik-crest Any updates on the PR?

**Comment by shaqnawe** [comment]
@ishans-crest Hello. I see an error remaining for get endpoint info action. I have checked and confirmed that the action output parameters are correctly sequenced. Can you please let me know what seems to be the issue? Here's the error in static test report. "Ordering of action output parameters for `get endpoint info` are not sequential or do not start at zero".

**Comment by ishans-crest** [comment]
image
Could you please verify the above data path for the `get endpoint info`  action? It should be `action_result.data.*.<name>`.

**Comment by shaqnawe** [comment]
> image Could you please verify the above data path for the `get endpoint info` action? It should be `action_result.data.*.<name>`.
> 
> please confirm this and I will make the changes accordingly.

Thank you for pointing this out. It should indeed be action_result.data.*.installed_product_codes and action_result.data.*.os_description.

**Comment by shaqnawe** [comment]
@ishans-crest We recently identified a response issue in V3 API that affects the current version of ptymv1 0.5.6 package. We have identified and updated the package to account for the issue. Is it possible to hold off on this PR until the next week so we can add the updated pytmv1 0.5.7 package? Besides requirements there should be no code changes.

**Comment by shaqnawe** [comment]
@ishans-crest I have updated the integration with the latest pytmv1 (0.5.8) package and have also corrected the sequencing of action outputs. We should be good to continue with the merge, please let me know if anything is needed from my end. Appreciate your patience and assistance with the PR.

**Comment by shaqnawe** [comment]
@ishans-crest Any updates on this? Thank you.

**Comment by ishans-crest** [comment]
@shaqnawe We have fixed the static failures and the pipelines are passing now, you can proceed with merging the PR.

**Comment by shaqnawe** [comment]
> @shaqnawe We have fixed the static failures and the pipelines are passing now, you can proceed with merging the PR.

@ishans-crest  Thank you!

**Review by t0mz06 — APPROVED** [review]

**Pull request merged**
